name: nixt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Nix
        uses: cachix/install-nix-action@v18
        with:
          nix_path: nixpkgs=channel:nixos-unstable

      - name: Setup Nixt
        run: nix-env -if https://github.com/nix-community/nixt/archive/master.tar.gz
      - name: Run Nixt
        working-directory: ./tests
        run: ./ut.sh

